#!/usr/bin/env bash

source ../../common.sh

make clean && make

BENCHMARK=carve.tasks
NAME_STRING="carve (non_rtm)"

THREADS=2
CLUSTERS=1
ARGS="--args 2 threads_${THREADS}_emap.out threads_${THREADS}_smap.out"
TEST_STRING="$THREADS threads $CLUSTERS cluster"
rm -rf RUN_OUTPUT/rigelprint.out RUN_OUTPUT/compare.out
echo "128" | $RIGELSIM $ARGS -threads $THREADS -clusters $CLUSTERS $BENCHMARK 2> threads_${THREADS}.out 1> cerr.out 
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
./rigeltopng output.pngdata threads_2.png
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > mt2diff.out ) then
  echo "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
  echo "===== Failed ($NAME_STRING $TEST_STRING)====="
fi

THREADS=4
CLUSTERS=1
ARGS="--args 2 threads_${THREADS}_emap.out threads_${THREADS}_smap.out"
TEST_STRING="$THREADS threads $CLUSTERS cluster"
rm -rf RUN_OUTPUT/rigelprint.out RUN_OUTPUT/compare.out
echo "128" | $RIGELSIM $ARGS -threads $THREADS -clusters $CLUSTERS $BENCHMARK 2> threads_${THREADS}.out 1> cerr.out 
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
./rigeltopng output.pngdata threads_4.png
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > mt4diff.out ) then
  echo "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
  echo "===== Failed ($NAME_STRING $TEST_STRING) ====="
fi
